services:
  client:
    image: 'jocelyntingting/fintrack-client'
    mem_limit: 128m
    hostname: client

  api:
    image: 'jocelyntingting/fintrack-api'
    mem_limit: 128m
    hostname: api
    environment:
      MONGO_URL: 'mongodb+srv://jocelyn:P0oWlauLqRjWWakW@fintrack.7nc8adn.mongodb.net/fintrack?retryWrites=true&w=majority&appName=fintrack'
      JWT_SECRET: 'secret'
      JWT_EXPIRES_IN: '90d'

  nginx:
    image: 'jocelyntingting/fintrack-nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
